# This workflow builds Sphinx documentation and deploys it to GitHub Pages.
# https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow

name: Deploy docs 

on:
    push:
        branches: [master] # branch to trigger deployment
    release:
        types: [published] # releases trigger deployment as well

jobs:
    pages:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        permissions:
            pages: write
            id-token: write
        steps:
            - id: deployment
              uses: sphinx-notes/pages@v3

