# This workflow builds Sphinx documentation and deploys it to GitHub Pages.

name: Build and publish docs

on:
    push:
        branches: [master] # branch to trigger deployment
    release:
        types: [published] # releases trigger deployment as well

jobs:
    pages:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        permissions:
            pages: write
            id-token: write
        steps:
            - id: deployment
              uses: sphinx-notes/pages@v3

